models/Post.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%post}}".
 *
 * @property int $id
 * @property string $title
 * @property int $status
 * @property string $intro
 * @property string $content
 * @property int $created_at
 * @property int $created_by
 * @property int $updated_at
 * @property int $updated_by
 */
class Post extends \app\components\BaseActiveRecord
{

    // {{{ Members
    const STATUS_DRAFT      = 1;
    const STATUS_PUBLISHED  = 2;
    const STATUS_ARCHIVED   = 3;
    /**
     * @var string
     */
    public $recordNameTemplate = '{title}';
    // }}}
    // {{{ tableName
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%post}}';
    } // }}}
    // {{{ behaviors
    public function behaviors()
    {
        return parent::behaviors();
    }  // }}}
    // {{{ rules
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'status', 'intro'], 'required'],
            [['status', 'created_at', 'created_by', 'updated_at', 'updated_by'], 'integer'],
            [['intro', 'content'], 'string'],
            [['title'], 'string', 'max' => 255],
        ];
    } // }}} 
    // {{{ attributeLabels
    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id'            => Yii::t('app', 'ID'),
            'title'         => Yii::t('app', 'Title'),
            'status'        => Yii::t('app', 'Status'),
            'intro'         => Yii::t('app', 'Intro'),
            'content'       => Yii::t('app', 'Content'),
            'created_at'    => Yii::t('app', 'Created At'),
            'created_by'    => Yii::t('app', 'Created By'),
            'updated_at'    => Yii::t('app', 'Updated At'),
            'updated_by'    => Yii::t('app', 'Updated By'),
        ];
    } // }}} 
    // {{{ getStatusOptions
    public function getStatusOptions()
    {
        return [
            self::STATUS_DRAFT => Yii::t('app','Draft'),
            self::STATUS_PUBLISHED => Yii::t('app','Published'),
            self::STATUS_ARCHIVED => Yii::t('app','Archived'),
        ];
    } // }}} 

    // {{{ find
    /**
     * {@inheritdoc}
     * @return PostQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new PostQuery(get_called_class());
    } // }}} 
}

controllers/ListfilterController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

use app\components\BaseController;

use app\models\Listfilter;
use app\models\ListfilterSearch;

/**
 * ListfilterController implements the CRUD actions for Listfilter model.
 */
class ListfilterController extends BaseController
{
    // {{{ Members
    public $fluid = true;
    // }}} 
    // {{{ behaviors
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'list', 'view', 'create', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index', 'list', 'view', 'create', 'update', 'delete'],
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'clearFilterState' => \thrieu\grid\ClearFilterStateBehavior::className(),
        ];
    } // }}} 
    // {{{ actionIndex
    /**
     * Lists all Listfilter models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ListfilterSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    } // }}} 
    // {{{ actionView
    /**
     * Displays a single Listfilter model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    } // }}} 
    // {{{ actionCreate
    /**
     * Creates a new Listfilter model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Listfilter();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', '<h4>'.Yii::t('app', 'Create New Item').'</h4>'.Yii::t('app', 'The List Filter #{id} has been created.', [
    'id' => $model->id,
]));
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    } // }}} 
    // {{{ actionUpdate
    /**
     * Updates an existing Listfilter model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', '<h4>'.Yii::t('app', 'Update Item').'</h4>'.Yii::t('app', 'The List Filter #{id} has been updated.', [
    'id' => $model->id,
]));
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    } // }}} 
    // {{{ actionApply
    public function actionApply($id)
    {
        if (($model = Listfilter::findOne($id)) !== null) {
            $state = \yii\helpers\Json::decode($model->filterState);
            // DEBUG \yii\helpers\VarDumper::dump($state, 10, true);
            $keyPrefix  = 'FilterStateBehavior';
            $route      = $model->route;
            $gridId     = '';
            $id         = $gridId !== null ? $gridId : '';
            $sessionKey = $keyPrefix . '_' . md5($route.$id);
            $session    = Yii::$app->session;
            $session->set($sessionKey, $state);
            Yii::$app->session->setFlash('success', 
                '<h4>'.Yii::t('app', 'Apply Saved Filter').'</h4>'
                .Yii::t('app', 'The saved filter <em>{name}</em> has been applied.', [ 'name'=>$model->name ] )
            );
            return $this->redirect([$model->route]); 
        } else {
            throw new NotFoundHttpException(Yii::t('app', 'The requested List Filter does not exist.'));
        }
    } // }}} 
    // {{{ actionDelete
    /**
     * Deletes an existing Listfilter model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if ($model->delete()) {
            Yii::$app->session->setFlash('success', '<h4>'.Yii::t('app', 'Delete Item').'</h4>'.Yii::t('app', 'The List Filter #{id} has been deleted.', [
    'id' => $model->id,
]));
        }

        return $this->redirect(['index']);
    } // }}} 
    // {{{ findModel
    /**
     * Finds the Listfilter model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Listfilter the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Listfilter::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('app', 'The requested List Filter does not exist.'));
        }
    } // }}} 
}

controllers/PostController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Post;
use app\models\PostSearch;
use app\components\BaseController;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends BaseController
{
    // {{{ Members
    public $fluid = true;
    // }}} 
    // {{{ behaviors
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                // Only apply ACF to these actions:
                'only' => ['index', 'view', 'create', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index', 'view'],
                        'roles' => ['admin','author', 'marketLaunchCoordinator'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['create', 'update', 'delete'],
                        'roles' => ['author'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            // For Clear Filters:
            'clearFilterState' => \thrieu\grid\ClearFilterStateBehavior::className(),
        ];
    } // }}} 
    // {{{ actionIndex
    /**
     * Lists all Post models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    } // }}} 
    // {{{ actionView
    /**
     * Displays a single Post model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $this->fluid = false;
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    } // }}} 
    // {{{ actionCreate
    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->fluid = false;
        $model = new Post();

        // Defaults via GET supplied?
        if(isset($_GET['Post'])) {
            $model->load(Yii::$app->request->get());
            // $model->validate();
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash(
                'success', 
                '<h4>'.Yii::t('app', 'Create New Post').'</h4>'
                .Yii::t('app', 'The post {recordName} has been created.', [
                    'recordName' => $model->recordName,
            ]));
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    } // }}}
    // {{{ actionUpdate
    /**
     * Updates an existing Post model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $this->fluid = false;
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash(
                'success', 
                '<h4>'.Yii::t('app', 'Update Post').'</h4>'
                .Yii::t('app', 'The post {recordName} has been updated.', [
                    'recordName' => $model->recordName,
            ]));
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    } // }}} 
    // {{{ actionDelete
    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if($model->delete()) {
            Yii::$app->session->setFlash(
                'success', 
                '<h4>'.Yii::t('app', 'Delete Post').'</h4>'
                .Yii::t('app', 'The post {recordName} has been deleted.', [
                    'recordName' => $model->recordName,
            ]));
        }
        return $this->redirect(['index']);
    } // }}} 
    // {{{ findModel
    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    } // }}} 
}

views/post/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Post */
/* @var $form yii\bootstrap\ActiveForm */
?>

<div class="post-form">

    <?php $form = ActiveForm::begin(['layout' => 'horizontal']); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'status')->dropDownList( $model->statusOptions, ['prompt'=>Yii::t('app', '(Select...)')] ) ?>

    <?= $form->field($model, 'intro')->widget(\yii2mod\markdown\MarkdownEditor::class, [
        'editorOptions' => [
            'showIcons' => ["code", "table"],
            'blockStyles' => [
                'italic' => '_',
            ],
        ],
    ]);  ?>

    <?= $form->field($model, 'content')->widget(\yii2mod\markdown\MarkdownEditor::class, [
        'editorOptions' => [
            'showIcons' => ["code", "table"],
            'blockStyles' => [
                'italic' => '_',
            ],
            'insertTexts' => [
                'table' => ['',   "Item | Value\r\n"
                                . "---- | ----:\r\n"
                                . "One  | 123.4"
                ],
            ],
        ],
    ]);  ?>


    <div class="form-group">
        <label class="control-label col-sm-3"></label>
        <div class="col-sm-6">
            <?= Html::submitButton('<span class="glyphicon glyphicon-ok"></span> ' . Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
            <?= Html::submitButton('<span class="glyphicon glyphicon-refresh"></span> ' . Yii::t('app', 'Reset'), ['class' => 'btn btn-primary']) ?>
        </div>
    </div>


    <?php ActiveForm::end(); ?>

</div>

views/post/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PostSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="post-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'intro') ?>

    <?= $form->field($model, 'content') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/post/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Post */

$this->title = Yii::t('app', 'Create Post');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Posts'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/post/index.php
<?php

use yii\bootstrap\Nav;
use yii\helpers\Html;
use yii\web\View;
use \app\widgets\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\PostSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

// Get user roles
$isAuthor = Yii::$app->user->can('author');

$this->title = Yii::t('app', 'Posts');
$this->params['breadcrumbs'][] = $this->title;
/* $this->context->leftMenu = [ // {{{ 
    [
        'label' => Yii::t('app', 'Operations'),
        'items' => [
            [ 'label' => Yii::t('app', 'New Post'), 'url' => ['create'], 'icon'=>'plus'],
            [ 'label' => Yii::t('app', 'Clear Filters'), 'url' => '#', 'bodyOptions'=>['id'=>'clearFiltersBtn'], 'icon'=>'refresh' ],
        ],
    ],
]; */ // }}} 
?>
<div class="post-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php echo Nav::widget([
        'items' => [
            [ 'label' => '<span class="glyphicon glyphicon-plus"></span>'.' '.Yii::t('app', 'New Post'), 'url' => ['create'], 'visible'=>$isAuthor],
            [ 'label' => '<span class="glyphicon glyphicon-refresh"></span>'.' '.Yii::t('app', 'Clear Filters'), 'url' => '#', 'linkOptions'=>['id'=>'clearFiltersBtn'] ],
            [ 'label' => '<span class="glyphicon glyphicon-filter"></span>'.' '.Yii::t('app', 'Save Filter Set'), 'url' => ['launch/save-filters', 'gridId'=>'', 'searchModel'=>'LaunchSearch'], 'linkOptions'=>['id'=>'saveFiltersBtn'] ],
            [ 'label' => '<span class="glyphicon glyphicon-th-list"></span>'.' '.Yii::t('app', 'All Saved Filter Sets'), 'url' => ['listfilter/index', 'ListfilterSearch[route]'=>'post/index'], 'linkOptions'=>['id'=>'listFiltersBtn'] ],
        ],
        'encodeLabels' => false,
        'options' => ['class' => 'nav-pills alert alert-info action-buttons'],
    ]);
    ?>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?php // {{{ Clear Filters Form ?>
    <?php  $form = Html::beginForm(['index'], 'post', ['id'=>'clear-filters-form', 'style'=>'display:inline']); ?>
    <?php  $form .= Html::hiddenInput('clear-state', '1'); ?>
    <?php  $form .= Html::hiddenInput('redirect-to', ''); ?>
    <?php  $form .= Html::endForm(); ?>
    <?php  echo $form; /* }}} */ ?>

    <?= GridView::widget([ // {{{ 
        'dataProvider' => $dataProvider,
        'as filterBehavior' => \thrieu\grid\FilterStateBehavior::className(),
        'filterModel' => $searchModel,
        'columns' => [
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update}',
                'contentOptions' => [ 'class' => 'text-center' ],
            ],
            'id',
            [
                'attribute' => 'title',
                'format'    => 'html',
                'value'     => function ($data) {
                    return Html::tag('b', Html::a($data->title, ['view', 'id'=>$data->id], ['title' => Yii::t('app', 'View Post: {recordName}', ['recordName'=>$data->recordName])]));
                },
            ],
            [
                'attribute' => 'status',
                'filter' => \app\models\Post::getStatusOptions(),
                'value' => function($data) {
                    return \app\models\Post::getStatusOptions()[$data->status];
                }
            ],
            'intro:ntext',
            'content:ntext',
            [
                'attribute' => 'created_at',
                'format' => 'datetime',
            ],
            //'created_by',
            //'updated_at',
            //'updated_by',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{delete}',
                'contentOptions' => [ 'class' => 'text-center' ],
            ],
        ],
    ]); /* }}} */?>
</div>

<?php $this->registerJs("
$('#clearFiltersBtn').on('click', function() { 
    $('#clear-filters-form').submit();
});
", View::POS_READY, 'my-button-handler' ); ?>

views/post/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Post */

$this->title = Yii::t('app', 'Update Post: ' . $model->title, [
    'nameAttribute' => '' . $model->title,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Posts'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="post-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/post/view.php
<?php

use yii\bootstrap\Nav;
use yii\helpers\Html;
use yii\helpers\Markdown;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Post */

// Get user roles
$isAuthor = Yii::$app->user->can('author');

$this->title = $model->recordName;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Posts'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$this->context->leftMenu = [
    [
        'label' => Yii::t('app', 'Operations'),
        'items' => [
            [ 'label' => Yii::t('app', 'Update'), 'url' => ['update', 'id'=>$model->id]],
        ],
    ],
];

?>
<div class="post-view">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php echo Nav::widget([
        'items' => [
            [ 'label' => '<span class="glyphicon glyphicon-pencil"></span>'.' '.Yii::t('app', 'Update'), 'url' => ['update', 'id'=>$model->id]],
        ],
        'encodeLabels' => false,
        'options' => ['class' => 'nav-pills alert alert-info action-buttons'],
    ]); ?>
    <div style="font-weight:bold;font-size:larger">
    <?= str_replace('<table>', '<table class="table table-striped">', Markdown::process(str_replace([".\r\n", "!\r\n"], [".  \r\n", "!  \r\n"], $model->intro), 'extra')) ?>
    </div>

    <p><?= str_replace('<table>', '<table class="table table-striped">', Markdown::process(str_replace([".\r\n", "!\r\n"], [".  \r\n", "!  \r\n"], $model->content), 'extra')) ?></p>

    <hr>

    <h3><?= Yii::t('app','Other Infos') ?></h3>
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            [
                'attribute' => 'status',
                'value' => $model->statusOptions[$model->status],
            ],
            'id',
        ],
    ]) ?>

    <!-- {{{ History -->
    <h3><?= Yii::t('app', 'History') ?></h3>
    <?= DetailView::widget([
       'model' => $model,
       'attributes' => [
           ['attribute'=>'created_at', 'format'=>'html', 'value'=>Yii::$app->formatter->asDateTime($model->created_at)],
           ['attribute'=>'createUserName', 'format'=>'html'],
           ['attribute'=>'updated_at', 'format'=>'html', 'value'=>Yii::$app->formatter->asDateTime($model->updated_at)],
           ['attribute'=>'updateUserName', 'format'=>'html'],
       ],
    ]) ?>
    <!-- }}} -->

    <?php if($isAuthor) : /* {{{ DELETE BTN */ ?>     <p>
        <?= Html::a('<span class="glyphicon glyphicon-trash"></span>&nbsp;'.Yii::t('app', 'Delete this record'), ['delete', 'id' => $model->id], [
            'title' => Yii::t('app','Click to confirm deleting post: {recordName}', ['recordName'=>$model->recordName]),
            'class' => 'btn btn-danger btn-xs hidden-print',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>
    <?php endif; /* }}} */ ?>

</div>