models/Listfilter.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%listfilter}}".
 *
 * @property int $id
 * @property string $name
 * @property string $route
 * @property string $filterState
 * @property int $sortorder
 */
class Listfilter extends \yii\db\ActiveRecord
{
    // {{{ behaviors
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => 'userId',
                    ActiveRecord::EVENT_BEFORE_UPDATE => 'userId',
                ]
            ],
        ];
    } // }}} 
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%listfilter}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'route'], 'required'],
            [['filterState'], 'string'],
            [['sortorder'], 'integer'], 
            [['name', 'route'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'route' => Yii::t('app', 'Route'),
            'filterState' => Yii::t('app', 'Filter State'),
            'sortorder' => Yii::t('app', 'Sort Order'), 
        ];
    }

    /**
     * @inheritdoc
     * @return ListfilterQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ListfilterQuery(get_called_class());
    }
}

controllers/ListfilterController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

use app\components\BaseController;

use app\models\Listfilter;
use app\models\ListfilterSearch;

/**
 * ListfilterController implements the CRUD actions for Listfilter model.
 */
class ListfilterController extends BaseController
{
    // {{{ Members
    public $fluid = true;
    // }}} 
    // {{{ behaviors
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'list', 'view', 'create', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index', 'list', 'view', 'create', 'update', 'delete'],
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'clearFilterState' => \thrieu\grid\ClearFilterStateBehavior::className(),
        ];
    } // }}} 
    // {{{ actionIndex
    /**
     * Lists all Listfilter models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ListfilterSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    } // }}} 
    // {{{ actionView
    /**
     * Displays a single Listfilter model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    } // }}} 
    // {{{ actionCreate
    /**
     * Creates a new Listfilter model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Listfilter();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', '<h4>'.Yii::t('app', 'Create New Item').'</h4>'.Yii::t('app', 'The List Filter #{id} has been created.', [
    'id' => $model->id,
]));
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    } // }}} 
    // {{{ actionUpdate
    /**
     * Updates an existing Listfilter model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', '<h4>'.Yii::t('app', 'Update Item').'</h4>'.Yii::t('app', 'The List Filter #{id} has been updated.', [
    'id' => $model->id,
]));
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    } // }}} 
    // {{{ actionApply
    public function actionApply($id)
    {
        if (($model = Listfilter::findOne($id)) !== null) {
            $state = \yii\helpers\Json::decode($model->filterState);
            // DEBUG \yii\helpers\VarDumper::dump($state, 10, true);
            $keyPrefix  = 'FilterStateBehavior';
            $route      = $model->route;
            $gridId     = '';
            $id         = $gridId !== null ? $gridId : '';
            $sessionKey = $keyPrefix . '_' . md5($route.$id);
            $session    = Yii::$app->session;
            $session->set($sessionKey, $state);
            Yii::$app->session->setFlash('success', 
                '<h4>'.Yii::t('app', 'Apply Saved Filter').'</h4>'
                .Yii::t('app', 'The saved filter <em>{name}</em> has been applied.', [ 'name'=>$model->name ] )
            );
            return $this->redirect([$model->route]); 
        } else {
            throw new NotFoundHttpException(Yii::t('app', 'The requested List Filter does not exist.'));
        }
    } // }}} 
    // {{{ actionDelete
    /**
     * Deletes an existing Listfilter model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if ($model->delete()) {
            Yii::$app->session->setFlash('success', '<h4>'.Yii::t('app', 'Delete Item').'</h4>'.Yii::t('app', 'The List Filter #{id} has been deleted.', [
    'id' => $model->id,
]));
        }

        return $this->redirect(['index']);
    } // }}} 
    // {{{ findModel
    /**
     * Finds the Listfilter model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Listfilter the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Listfilter::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('app', 'The requested List Filter does not exist.'));
        }
    } // }}} 
}

views/listfilter/_form.php
<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Listfilter */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?= $model->isNewRecord ? '(New Item)' : $model->name ?></h3>
    </div>
    <div class="listfilter-form  panel-body">

        <?php $form = ActiveForm::begin([ 'layout' => 'horizontal' ] ); ?>

        <?= $form->errorSummary($model) ?> <!-- ADDED HERE -->

        <?= $form->field($model, 'name', ['inputOptions' => ['autofocus' => 'autofocus']])->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'sortorder')->textInput() ?> 

        <?= $form->field($model, 'route')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'filterState')->textarea(['rows' => 6]) ?>

        <div class="form-group">
            <label class="control-label col-sm-3"></label>
            <div class="col-sm-6">
                <?= Html::submitButton($model->isNewRecord ? '<span class="glyphicon glyphicon-ok"></span> ' . Yii::t('app', 'Create') : '<span class="glyphicon glyphicon-ok"></span> ' . Yii::t('app', 'Save'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            <?= Html::resetButton('<span class="glyphicon glyphicon-refresh"></span> ' . Yii::t('app', 'Reset') , ['class' => 'btn btn-primary']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>

views/listfilter/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ListfilterSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="listfilter-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'sortorder') ?> 
 
    <?= $form->field($model, 'route') ?>

    <?= $form->field($model, 'filterState') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/listfilter/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Listfilter */

$this->title = Yii::t('app', 'Create List Filter');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Listfilters'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="listfilter-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/listfilter/index.php
<?php

use yii\helpers\Html;
//use yii\grid\GridView;
use yii\bootstrap\Button;
use yii\bootstrap\Nav;
use yii\web\View;

use \app\widgets\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ListfilterSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'List Filters');
// $this->params['breadcrumbs'][] = [ 'label' => Yii::t('CATEGORY', 'MODULENAME', 'url' => [ '/URL'] ];
$this->params['breadcrumbs'][] = $this->title;
/* {{{ 
$this->context->leftMenu = [
    [
        'label' => Yii::t('app', 'Operations'),
        'items' => [
            [ 'label' => Yii::t('app', 'Clear Filters'),        'url' => '#', 'bodyOptions'=>['id'=>'clearFiltersBtn'], 'icon'=>'refresh' ],
        ],
    ],
]; }}} */ 
?>
<div class="listfilter-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?php echo Nav::widget([
        'items' => [
             [ 'label' => '<span class="glyphicon glyphicon-refresh"></span>'.' '.Yii::t('app', 'Clear Filters'), 'url' => '#', 'linkOptions'=>['id'=>'clearFiltersBtn'] ],
        ],
        'encodeLabels' => false,
        'options' => ['class' => 'nav-pills alert alert-info action-buttons'],
        ]); ?>

    <p>
        <?= Yii::t('app', 'To create a new List Filter, set filters in the Launches or Action Items grid view, then click Create List Filter') ?>
        <?= '' // DEACTIVATED Html::a('<span class="glyphicon glyphicon-plus"></span> ' . Yii::t('app', 'Create New List Filter'), ['create'], ['class' => 'btn btn-success']) ?>

    <?php $form = Html::beginForm(['index'], 'post', ['id'=>'clear-filters-form', 'style'=>'display:inline']);
    $form .= Html::hiddenInput('clear-state', '1');
    $form .= Html::hiddenInput('redirect-to', '');
    // $form .= Button::widget(['label' => Yii::t('app', 'Reset Filter'), 'options' => ['class'=>'btn btn-primary btn-sm']]);
    $form .= Html::endForm();
    echo $form; ?>

    </p>

    <?= GridView::widget([
        'id' => 'listfilter-grid-view',
        'as filterBehavior' => \thrieu\grid\FilterStateBehavior::className(),
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'options' => ['class' => 'grid-view table-responsive'],
        'tableOptions' => ['class' => 'table table-striped table-condensed'], // table-bordered 
        'rowOptions'   => function ($model, $key, $index, $grid) {
            return ['data-id' => $model->id];
        },
        'columns' => [
            [
                'class' => 'yii\grid\ActionColumn', 
                'template' => '{view} {update}',
                'contentOptions' => [ 'class' => 'text-center', 'style'=>'white-space:nowrap' ],
            ],
            [
                'class' => 'yii\grid\ActionColumn', 
                'template' => '{apply}',
                'contentOptions' => [ 'class' => 'text-center' ],
                'buttons' => [
                    'apply' => function ($url, $model, $key) {
                        list($controller, $action) = explode('/', $model->route);
                        return Html::a('<span class="glyphicon glyphicon-filter"></span>', ['/listfilter/apply', 'id'=>$model->id], ['title'=>Yii::t('app','Apply List Filter: {name}', ['name'=>$model->name])]);
                    },
                ]
            ],
            // ['class' => 'yii\grid\SerialColumn'],

            // 'id',
            [
                'attribute' => 'sortorder',
                'contentOptions' => [ 'class' => 'text-center' ],
            ],
            [
                'attribute' => 'name',
                'format' => 'html',
                'value' => function ($model, $key, $index, $column) {
                    return '<b>'.Html::a($model->name, ['view', 'id' => $model->id], ['title'=>Yii::t('app','View List Filter: {name}', ['name'=>$model->name])]).'</b>';
                },
            ],
            'route',
            'filterState:ntext',

            [
                'class' => 'yii\grid\ActionColumn', 
                'template' => '{delete}',
                'contentOptions' => [ 'class' => 'text-center' ],
            ],
        ],
    ]); ?>

</div>

<?php $this->registerJs("
$('#clearFiltersBtn').on('click', function() { 
    $('#clear-filters-form').submit();
});
", View::POS_READY, 'my-button-handler' ); ?>

views/listfilter/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Listfilter */

$this->title = Yii::t('app', 'Update List Filter');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Listfilters'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="listfilter-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/listfilter/view.php
<?php

use yii\helpers\Html;
use \yii\helpers\Json;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Listfilter */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'List Filters'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

list($controller, $action)=explode('/', $model->route);
?>
<div class="listfilter-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-search"></span> ' . Yii::t('app', 'Apply'), ['apply', 'id' => $model->id], ['class' => 'btn btn-success']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-remove"></span> ' . Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            // 'id',
            'sortorder',
            [
                'attribute'=>'name',
                'format'=>'html',
                'value'=>'<strong>'.$model->name.'</strong>',
            ],
            'route',
            [
                'attribute'=>'filterState',
                'format'=>'ntext',
                'value' => Json::encode(Json::decode($model->filterState), JSON_PRETTY_PRINT)
            ],
        ],
    ]) ?>

</div>