controllers/PostController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Post;
use app\models\PostSearch;
use app\components\BaseController;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends BaseController
{
    // {{{ Members
    public $fluid = true;
    // }}} 
    // {{{ behaviors
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                // Only apply ACF to these actions:
                'only' => ['index', 'view', 'create', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index', 'view'],
                        'roles' => ['admin','author', 'marketLaunchCoordinator'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['create', 'update', 'delete'],
                        'roles' => ['author'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            // For Clear Filters:
            'clearFilterState' => \thrieu\grid\ClearFilterStateBehavior::className(),
        ];
    } // }}} 
    // {{{ actionIndex
    /**
     * Lists all Post models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    } // }}} 
    // {{{ actionView
    /**
     * Displays a single Post model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $this->fluid = false;
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    } // }}} 
    // {{{ actionCreate
    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->fluid = false;
        $model = new Post();

        // Defaults via GET supplied?
        if(isset($_GET['Post'])) {
            $model->load(Yii::$app->request->get());
            // $model->validate();
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash(
                'success', 
                '<h4>'.Yii::t('app', 'Create New Post').'</h4>'
                .Yii::t('app', 'The post {recordName} has been created.', [
                    'recordName' => $model->recordName,
            ]));
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    } // }}}
    // {{{ actionUpdate
    /**
     * Updates an existing Post model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $this->fluid = false;
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash(
                'success', 
                '<h4>'.Yii::t('app', 'Update Post').'</h4>'
                .Yii::t('app', 'The post {recordName} has been updated.', [
                    'recordName' => $model->recordName,
            ]));
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    } // }}} 
    // {{{ actionDelete
    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if($model->delete()) {
            Yii::$app->session->setFlash(
                'success', 
                '<h4>'.Yii::t('app', 'Delete Post').'</h4>'
                .Yii::t('app', 'The post {recordName} has been deleted.', [
                    'recordName' => $model->recordName,
            ]));
        }
        return $this->redirect(['index']);
    } // }}} 
    // {{{ findModel
    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    } // }}} 
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Html;
use yii\web\Controller;
use yii\web\Response;
use yii\web\NotFoundHttpException;

use app\models\LoginForm;
use app\models\ContactForm;
use app\components\BaseController;
use app\components\General;

class SiteController extends BaseController
{
    // {{{ behaviors
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'allow' => false,
                        'actions' => ['rules'],
                    ],
  [
                        'actions' => ['rules', 'logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    } // }}} 
    // {{{ actions
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'manage-settings' => [
                'class' => \yii2mod\settings\actions\SettingsAction::class,
                // also you can use events as follows:
                'on beforeSave' => function ($event) {
                    // your custom code
                },
                'on afterSave' => function ($event) {
                    // your custom code
                },
                'modelClass' => \app\models\forms\AppParamsForm::class,

                'view' => 'settings',
                'successMessage' => '<h4>'.Yii::t('app','Saving Settings').'</h4>'.Yii::t('app','The settings have been saved successfully.'),


            ],
            'page' => [
                'class' => 'yii\web\ViewAction',
            ],
        ];
    } // }}} 
    // {{{ actionIndex
    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $this->fluid = true;
        $report = null;

        // if(!Yii::$app->user->isGuest)
        //    $report = Yii::$app->runAction('report/responses-by-markets', ['partial'=>true]);
        // return $this->render('index', ['report'=>$report]);
        return $this->render('index');
    } // }}} 
    // {{{ actionLogin
    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    } // }}} 
    // {{{ actionLogout
    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    } // }}} 
    // {{{ actionContact
    /** 
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->settings->get('AppParamsForm', 'contactEmail'))) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    } // }}} 
    // {{{ actionAbout
    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    } // }}} 
    // {{{ actionRules
    /**
     * Displays the Rules page.
     *
     * @return string
     */
    public function actionRules()
    {
        return $this->render('rules');
    } // }}} 
    // {{{ actionSendMail
    /**
     * Sends a mail using mailerqueue.
     *
     * @return string
     */
    public function actionSendMail()
    {
        for($i=0; $i<1; $i++) {
            Yii::$app->mailqueue->compose('send-mail', ['data' => ['description'=>'Mail #'.($i+1)]])
                ->setFrom('joachim.pt.werner@opel.com')
                ->setTo('joachim.pt.werner@opel.com')
                ->setSubject('Test mailqueue #'.($i+1))
                ->setTextBody('Bla Blub...')
                ->queue();
        }
        return $this->render('about');
    } // }}} 
    // {{{ actionHelp
    public function actionHelp($page='README')
    {
        // $this->fluid=true;
        if(!file_exists(Yii::getAlias('@app/views/site/markdown/'.$page.'.md')))
            throw new NotFoundHttpException(Yii::t('app', 'The requested help page does not exist.'));
        $markdown = file_get_contents(Yii::getAlias('@app/views/site/markdown/'.$page.'.md'));
        return $this->render('help', ['page'=>$page, 'markdown'=>$markdown]);
    } // }}} 
    // {{{ actionRunInitialMigrations
    /**
     * Run initial database migrations
     */
    public function actionRunInitialMigrations() {
        $this->layout = false;
        echo '<h1>Running Database Migrations</h1>';
        echo '<pre>';
        echo Html::tag('h2', 'Create RBAC Tables');
        General::runConsoleActionFromWebApp('migrate', ['migrationPath' => '@yii/rbac/migrations', 'interactive' => false]);
        echo Html::tag('h2', 'Run yii2-user module migrations');
        General::runConsoleActionFromWebApp('migrate', ['migrationPath'=>'@vendor/dektrium/yii2-user/migrations', 'interactive' => false]);
        echo Html::tag('h2', 'Run yii2-settings module migrations');
        General::runConsoleActionFromWebApp('migrate', ['migrationPath'=>'@vendor/yii2mod/yii2-settings/migrations', 'interactive' => false]);
        echo Html::tag('h2', 'Run Application migrations');
        General::runConsoleActionFromWebApp('migrate', ['interactive' => false]);
        echo Html::tag('h2', 'Run lookup module migrations');
        General::runConsoleActionFromWebApp('migrate', ['migrationPath'=>'@app/modules/lookup/migrations', 'interactive' => false]);
        echo Html::tag('h2', 'Run Application Settings creation');
        General::runConsoleActionFromWebApp('init-app');
        echo Html::tag('h2', 'FINISHED MIGRATIONS :-)');
        echo '<pre>';
        die;
    } // }}}
}

views/site/_news_list_item.php
<?php
// Script to display a single list item
use yii\helpers\Html;

use app\models\Post;

$labels = [
    Post::STATUS_DRAFT      => ['class'=>'warning', 'label' => Yii::t('app','Draft')],
    Post::STATUS_PUBLISHED  => ['class'=>'success', 'label' => Yii::t('app','Published')],
    Post::STATUS_ARCHIVED   => ['class'=>'default', 'label' => Yii::t('app','Archived')],
];
?>
 
<article class="list-item col-sm-12" data-key="<?= $model['id'] ?>">
    <strong><?= Yii::$app->formatter->asDateTime($model['updated_at'], 'short') ?></strong><br />
    <p><?= Html::encode($model['title']); ?> - <?= Yii::$app->opelUtils->limitWords($model['intro'], Yii::$app->settings->get('AppParamsForm', 'homeNewsItemWordLimit')) ?><br>
        <?= Html::a('<span class="glyphicon glyphicon-chevron-right"></span> '.Yii::t('app','More...'), ['post/view', 'id'=>$model['id']], ['title'=>Yii::t('app', 'Read more on this topic: {title}', ['title'=>$model['title']])]) ?>
        <?php if(Yii::$app->user->can('author')) : ?>
        <span class="label label-<?= $labels[$model['status']]['class'] ?>"><?= $labels[$model['status']]['label'] ?></span>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['post/update', 'id'=>$model['id']], ['class'=>'btn btn-success btn-xs']) ?>
        <?php endif; ?>
    </p>
    
</article>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use yii\web\View;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <p><strong><?= Yii::t('app','Note:') ?> </strong><?= Yii::t('app','If you require a different Verification Code, click on the code above.') ?></p>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

<?php $this->registerJs("
$('#contactform-verifycode-image').css('cursor', 'pointer');
$('#contactform-verifycode-image').attr('title', '" . Yii::t('app','Note: If you require a different Verification Code, click on this code here.') . "');
", View::POS_READY, 'css' ); ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/settings.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $model \app\models\forms\ConfigurationForm */
/* @var $this \yii\web\View */

$this->title = Yii::t('app', 'Manage Application Settings');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Settings')];
?>

<div class="settings-form">

    <h1><?= Html::encode('Manage Application Settings') ?></h1>

    <p class="well">
        <?= Yii::t('app','Sections:') ?>
        <a href="#emailAddresses"><?= Yii::t('app', 'Email Addresses') ?></a> | 
        <a href="#homePage"><?= Yii::t('app', 'Home Page') ?></a> | 
        <a href="#sendLaunchEmail"><?= Yii::t('app', 'Send Launch Email') ?></a> | 
        <a href="#actionItems"><?= Yii::t('app', 'Action Items') ?></a> | 
        <a href="#markets"><?= Yii::t('app', 'Markets') ?></a> | 
        <a href="#otherSettings"><?= Yii::t('app', 'Other Settings') ?></a> 

    <?php $form = ActiveForm::begin(); ?>

    <fieldset id="emailAddresses">
    <legend><?= Yii::t('app','Email Addresses') ?></legend>
    <p><?= Yii::t('app', 'These email address settings are used to send notification emails.') ?></p>
    <?php echo $form->field($model, 'contactEmail')->hint('Email address which receives contact form enquiries'); ?>
    <?php echo $form->field($model, 'adminEmail'); ?>
    </fieldset>

    <fieldset id="homePage">
    <legend><?= Yii::t('app','Home Page') ?></legend>
    <?php echo $form->field($model, 'homeNewsItemsPerPage')->textInput()->hint('How many news items shall be displayed on the Home page?'); ?>
    <?php echo $form->field($model, 'homeNewsItemWordLimit')->textInput()->hint('How many words per news item shall be displayed on the Home page?'); ?>
    </fieldset>

    <fieldset id="sendLaunchEmail">
    <legend><?= Yii::t('app','Send Launch Email') ?></legend>
    <p><?= Yii::t('app', 'These settings are used as default when sending a lauch notification email.') ?></p>
    <?php echo $form->field($model, 'launchSendEmailSubject')->textInput()->hint(Yii::t('app','Message subject. The placeholders {{LAUNCHNAME} and {{APPNAME}} get replaced.')); ?>
    <?php echo $form->field($model, 'launchSendEmailBcc')->hint('Email address to be set on Bcc.'); ?>
    <?php echo $form->field($model, 'launchSendEmailMessage')->textarea(['columns'=>40, 'rows'=>4])->hint(Yii::t('app','Message text. The placeholders {{LINK} and {{APPNAME}} get replaced.')); ?>
    </fieldset>

    <fieldset id="actionItems">
    <legend><?= Yii::t('app','Action Items') ?></legend>
    <?php echo $form->field($model, 'actionItemMarketCommentsMaxChars')->textInput()->hint(Yii::t('app','How many characters are allowed in comments?')) ?>
    <?php echo $form->field($model, 'actionItemMarketTokenExpirationTime')->textInput()->hint(Yii::t('app','How many hours shall a token to update an action item be valid?')) ?>
    <?php echo $form->field($model, 'actionItemMarketTokenUpdateTime')->textInput()->hint(Yii::t('app','How many hours shall a token to update an action item again be valid?')) ?>
    </fieldset>

    <fieldset id="markets">
    <legend><?= Yii::t('app','Top X Markets') ?></legend>
    <?php echo $form->field($model, 'topXMarkets')->textarea(['columns'=>40, 'rows'=>3])->hint(Yii::t('app','Define Top X Market groups. Enter a label and 2-char. country codes, separated by >. Separate Top X groups by |.').'<br>'.Yii::t('app', 'Example: <em>Top 5>DE;ES;FR;IT;UK|Top 9>AT;FR;DE;IT;PL;PT;ES;CH;UK</em>')) ?>
    <?php echo $form->field($model, 'reportResponsesByMarketShowTopX')->textInput()->hint(Yii::t('app',"Which Top X Market group to show in report 'Responses by Market'.") . ' ' . Yii::t('app', "Must exist as a key in setting 'Top X Markets").'<br>'.Yii::t('app', 'Example: <em>Top 9</em>')) ?>
    </fieldset>

    <fieldset id="otherSettings">
    <legend><?= Yii::t('app','Other Settings') ?></legend>
    <?php echo $form->field($model, 'launchLegend')->textarea(['columns'=>40, 'rows'=>8]) ?>
    </fieldset>

    <?= Html::submitButton('<span class="glyphicon glyphicon-ok"></span> ' . Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    <?= Html::resetButton('<span class="glyphicon glyphicon-refresh"></span> ' . Yii::t('app', 'Reset'), ['class' => 'btn btn-primary']) ?>

    <?php ActiveForm::end(); ?>

</div>